name: BindPlane Full Infra Setup

on:
  workflow_dispatch:
    inputs:
      project_id: { required: true }
      region: { default: us-central1 }
      zone: { default: us-central1-a }
      vm_name: { required: true }
      bucket_name: { required: true }
      db_user: { required: true }
      db_pass: { required: true }
      bp_admin_user: { required: true }
      bp_admin_pass: { required: true }

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6

    - name: Authenticate to GCP
      run: |
      echo '${{ secrets.GCP_SA_KEY }}' > gcp-key.json
      chmod 600 gcp-key.json
       echo "GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/gcp-key.json" >> $GITHUB_ENV

    - name: Terraform Init
      run: terraform init -reconfigure

    - name: Terraform Apply
      run: |
        terraform apply -auto-approve \
        -var="project_id=${{ github.event.inputs.project_id }}" \
        -var="region=${{ github.event.inputs.region }}" \
        -var="zone=${{ github.event.inputs.zone }}" \
        -var="vm_name=${{ github.event.inputs.vm_name }}" \
        -var="bucket_name=${{ github.event.inputs.bucket_name }}" \
        -var="db_user=${{ github.event.inputs.db_user }}" \
        -var="db_pass=${{ github.event.inputs.db_pass }}" \
        -var="bp_admin_user=${{ github.event.inputs.bp_admin_user }}" \
        -var="bp_admin_pass=${{ github.event.inputs.bp_admin_pass }}" \
        -var="bindplane_license_key=${{ secrets.BINDPLANE_LICENSE_KEY }}" \
        -var="credentials_file=$(pwd)/gcp-key.json"

    - name: Show Outputs
      run: terraform output
